# Generated by Django 4.1.3 on 2022-11-19 22:09

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('activation_token', models.CharField(max_length=32)),
                ('activation_step', models.CharField(choices=[(website.models.UserActivationSteps['EMAIL'], 'WAIT_FOR_EMAIL'), (website.models.UserActivationSteps['ADMIN'], 'WAIT_FOR_ADMIN'), (website.models.UserActivationSteps['READY'], 'READY')], default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('wish_file', models.FileField(upload_to=website.models.get_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activation_token', models.CharField(max_length=32)),
                ('activation_step', models.CharField(choices=[(website.models.FileActivationSteps['EMAIL'], 'WAIT_FOR_EMAIL'), (website.models.FileActivationSteps['READY'], 'READY')], default=None, max_length=50)),
            ],
        ),
    ]
