# Generated by Django 3.2.9 on 2021-11-14 20:50

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('activation_token', models.CharField(max_length=50)),
                ('activation_step', models.CharField(choices=[(website.models.ActivationSteps['EMAIL'], 'WAIT_FOR_EMAIL'), (website.models.ActivationSteps['ADMIN'], 'WAIT_FOR_ADMIN'), (website.models.ActivationSteps['READY'], 'READY')], max_length=5)),
            ],
        ),
    ]
